[phases.setup]
nixPkgs = ["php81", "php81Packages.composer", "nodejs-18_x"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "php artisan package:discover"
]

[phases.build]
cmds = [
    "npm install --production",
    "npm run prod || npm run build || npm run production || echo 'No se encontró un comando de producción para npm'",
    "php artisan optimize",
    "php artisan config:cache",
    "php artisan route:cache",  # Descomentado para caché de rutas
    "php artisan view:cache",
    "php artisan migrate --force || echo 'No se pudieron ejecutar las migraciones'"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"